//document.write('<script src="../../js/url.js"></script> ');
var baseUrl="http://127.0.0.1:8081";//开发本地
//var baseUrl="";//测试环境
//var baseUrl="";//正式环境
var baseHtmlUrl="http://127.0.0.1:8080";//开发本地
//var baseHtmlUrl="";//测试环境
//var baseHtmlUrl="";//正式环境
document.write('<script src="'+baseHtmlUrl+'/commonJs/jquery.js"></script> ');
document.write('<script src="'+baseHtmlUrl+'/commonJs/bootstrap.js"></script> ');
document.write('<script src="'+baseHtmlUrl+'/commonJs/template.js"></script> ');
document.write('<script src="'+baseHtmlUrl+'/commonJs/json2.js"></script> ');
